settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: www-doonsec-com
    name: www.doonsec.com
    description: '洞见官网'
    url: 'http://www.doonsec.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: wechat-doonsec-com
    name: wechat.doonsec.com
    description: '洞见微信'
    url: 'https://wechat.doonsec.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: hub.datasec.wiki
    name: hub.datasec.wiki
    description: '洞见微信'
    url: 'https://hub.datasec.wiki'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: m.wechat-doonsec-com
    name: m.wechat.doonsec.com
    description: '洞见微信'
    url: 'https://m.wechat.doonsec.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

